const fs = require('fs');
const path = require('path');

const targetFile = path.resolve(__dirname, '../travel-buddy-backend/services/parcelLookup.js');

const lines = [
  "// services/parcelLookup.js",
  "// Centralized federation layer for active (PostParcel) and archived (ParcelHistory) parcel records.",
  "",
  "const PostParcel = require('../models/PostParcel');",
  "const ParcelHistory = require('../models/ParcelHistory');",
  "const User = require('../models/User');",
  "const WalletTransaction = require('../models/WalletTransaction');",
  "const Conversation = require('../models/Conversation');",
  "const { computeFraudScore } = require('./fraudScore');",
  "",
  "/**",
  " * Transforms a ParcelHistory document into standard PostParcel document shape.",
  " */",
  "function adaptHistoryDoc(doc) {",
  "  if (!doc) return null;",
  "  const s = doc.snapshot || {};",
  "  return {",
  "    ...s,",
  "    _id: doc.originalParcelId || doc._id,",
  "    originalParcelId: doc.originalParcelId,",
  "    historyId: doc._id,",
  "    orderId: doc.orderId || s.orderId,",
  "    status: doc.finalStatus || s.status,",
  "    sender: doc.sender || s.sender,",
  "    acceptedBy: doc.acceptedBy || s.acceptedBy,",
  "    cancelledBy: doc.cancelledBy || s.cancelledBy,",
  "    deliveredAt: s.deliveredAt || (doc.finalStatus === 'delivered' ? doc.completedAt : null),",
  "    cancelledAt: s.cancelledAt || (doc.finalStatus === 'cancelled' ? doc.completedAt : null),",
  "    cancellationReason: s.cancellationReason || '',",
  "    cancellationFee: s.cancellationFee || 0,",
  "    cancellationTravelerCompensation: s.cancellationTravelerCompensation || 0,",
  "    cancellationPlatformFee: s.cancellationPlatformFee || 0,",
  "    createdAt: s.createdAt || doc.createdAt,",
  "    updatedAt: doc.completedAt || doc.updatedAt || s.updatedAt,",
  "    isArchived: true,",
  "    price: s.price || 0,",
  "    heldAmount: s.heldAmount || 0,",
  "    chargedAmount: s.chargedAmount || 0,",
  "    platformCommission: s.platformCommission || 0,",
  "    travelerEarning: s.travelerEarning || 0,",
  "    fromCity: s.fromCity || '',",
  "    toCity: s.toCity || '',",
  "    description: s.description || '',",
  "    weight: s.weight || 0,",
  "    pickupDate: s.pickupDate || null,",
  "    paymentStatus: s.paymentStatus || 'held',",
  "    paymentMethod: s.paymentMethod || 'wallet',",
  "    category: s.category || 'general',",
  "    priority: s.priority || 'normal',",
  "    trackingHistory: s.trackingHistory || []",
  "  };",
  "}",
  "",
  "/**",
  " * Finds a parcel anywhere: first active, then historical archive.",
  " */",
  "async function findParcelAnywhere(idOrOrderId) {",
  "  if (!idOrOrderId) return null;",
  "",
  "  let active = null;",
  "  try {",
  "    active = await PostParcel.findOne({",
  "      $or: [{ _id: idOrOrderId }, { orderId: idOrOrderId }]",
  "    }).lean();",
  "  } catch (err) {",
  "    active = await PostParcel.findOne({ orderId: idOrOrderId }).lean();",
  "  }",
  "  if (active) return { ...active, isArchived: false };",
  "",
  "  let history = null;",
  "  try {",
  "    history = await ParcelHistory.findOne({",
  "      $or: [{ originalParcelId: idOrOrderId }, { _id: idOrOrderId }, { orderId: idOrOrderId }]",
  "    })",
  "    .populate('sender', 'firstName lastName email phone profilePhoto walletBalance rating senderPublicId isVerified')",
  "    .populate('acceptedBy', 'firstName lastName email phone profilePhoto walletBalance rating ratingCount travelerPublicId isVerified isOnline')",
  "    .populate('cancelledBy', 'firstName lastName email')",
  "    .lean();",
  "  } catch (err) {",
  "    history = await ParcelHistory.findOne({ orderId: idOrOrderId })",
  "      .populate('sender', 'firstName lastName email phone profilePhoto walletBalance rating senderPublicId isVerified')",
  "      .populate('acceptedBy', 'firstName lastName email phone profilePhoto walletBalance rating ratingCount travelerPublicId isVerified isOnline')",
  "      .populate('cancelledBy', 'firstName lastName email')",
  "      .lean();",
  "  }",
  "",
  "  return history ? adaptHistoryDoc(history) : null;",
  "}",
  "",
  "/**",
  " * Federates active and archived parcels for admin table view with full filtering and pagination.",
  " */",
  "async function getAdminParcels({ search, status, page = 1, limit = 20, sort = { createdAt: -1 } }) {",
  "  const pageNum = Math.max(1, parseInt(page, 10) || 1);",
  "  const limitNum = Math.min(100, Math.max(1, parseInt(limit, 10) || 20));",
  "  const skip = (pageNum - 1) * limitNum;",
  "",
  "  const activeFilter = {};",
  "  const historyFilter = {};",
  "",
  "  if (status && status !== 'all') {",
  "    if (status === 'delivered') {",
  "      activeFilter.status = 'delivered';",
  "      historyFilter.finalStatus = 'delivered';",
  "    } else if (status === 'cancelled') {",
  "      activeFilter.status = { $regex: /^cancelled/ };",
  "      historyFilter.finalStatus = 'cancelled';",
  "    } else {",
  "      activeFilter.status = status;",
  "      historyFilter.finalStatus = 'NEVER_MATCH';",
  "    }",
  "  }",
  "",
  "  if (search) {",
  "    const escaped = search.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');",
  "    const regex = { $regex: escaped, $options: 'i' };",
  "",
  "    activeFilter.$or = [",
  "      { orderId: regex },",
  "      { fromCity: regex },",
  "      { toCity: regex },",
  "      { description: regex }",
  "    ];",
  "",
  "    historyFilter.$or = [",
  "      { orderId: regex },",
  "      { 'snapshot.fromCity': regex },",
  "      { 'snapshot.toCity': regex },",
  "      { 'snapshot.description': regex }",
  "    ];",
  "",
  "    const matchingUsers = await User.find({",
  "      $or: [{ firstName: regex }, { lastName: regex }, { email: regex }, { phone: regex }]",
  "    }).select('_id').lean();",
  "",
  "    if (matchingUsers.length > 0) {",
  "      const uIds = matchingUsers.map(u => u._id);",
  "      activeFilter.$or.push({ sender: { $in: uIds } }, { acceptedBy: { $in: uIds } });",
  "      historyFilter.$or.push({ sender: { $in: uIds } }, { acceptedBy: { $in: uIds } });",
  "    }",
  "  }",
  "",
  "  const [activeCount, historyCount] = await Promise.all([",
  "    PostParcel.countDocuments(activeFilter),",
  "    historyFilter.finalStatus === 'NEVER_MATCH' ? 0 : ParcelHistory.countDocuments(historyFilter)",
  "  ]);",
  "",
  "  const total = activeCount + historyCount;",
  "",
  "  const [activeDocs, historyDocs] = await Promise.all([",
  "    PostParcel.find(activeFilter)",
  "      .populate('sender', 'firstName lastName email phone')",
  "      .populate('acceptedBy', 'firstName lastName email phone')",
  "      .sort(sort)",
  "      .limit(pageNum * limitNum)",
  "      .lean(),",
  "    historyFilter.finalStatus === 'NEVER_MATCH' ? [] : ParcelHistory.find(historyFilter)",
  "      .populate('sender', 'firstName lastName email phone')",
  "      .populate('acceptedBy', 'firstName lastName email phone')",
  "      .populate('cancelledBy', 'firstName lastName email phone')",
  "      .sort({ completedAt: -1 })",
  "      .limit(pageNum * limitNum)",
  "      .lean()",
  "  ]);",
  "",
  "  const unified = [",
  "    ...activeDocs.map(d => ({ ...d, isArchived: false })),",
  "    ...historyDocs.map(adaptHistoryDoc)",
  "  ];",
  "",
  "  unified.sort((a, b) => {",
  "    const dateA = new Date(a.createdAt || a.completedAt || 0).getTime();",
  "    const dateB = new Date(b.createdAt || b.completedAt || 0).getTime();",
  "    return dateB - dateA;",
  "  });",
  "",
  "  const paged = unified.slice(skip, skip + limitNum);",
  "",
  "  return {",
  "    parcels: paged,",
  "    total,",
  "    page: pageNum,",
  "    limit: limitNum,",
  "    totalPages: Math.ceil(total / limitNum) || 1",
  "  };",
  "}",
  "",
  "/**",
  " * Returns full parcel detail for admin view, regardless of active or archived status.",
  " */",
  "async function getAdminParcelDetail(idOrOrderId) {",
  "  let parcel = null;",
  "",
  "  try {",
  "    parcel = await PostParcel.findById(idOrOrderId)",
  "      .populate('sender', 'firstName lastName email phone profilePhoto walletBalance rating senderPublicId isVerified')",
  "      .populate('acceptedBy', 'firstName lastName email phone profilePhoto walletBalance rating ratingCount travelerPublicId isVerified isOnline')",
  "      .populate('cancelledBy', 'firstName lastName email')",
  "      .populate('adminNotes.adminId', 'firstName lastName email')",
  "      .lean();",
  "  } catch (e) {}",
  "",
  "  if (!parcel) {",
  "    parcel = await PostParcel.findOne({ orderId: idOrOrderId })",
  "      .populate('sender', 'firstName lastName email phone profilePhoto walletBalance rating senderPublicId isVerified')",
  "      .populate('acceptedBy', 'firstName lastName email phone profilePhoto walletBalance rating ratingCount travelerPublicId isVerified isOnline')",
  "      .populate('cancelledBy', 'firstName lastName email')",
  "      .populate('adminNotes.adminId', 'firstName lastName email')",
  "      .lean();",
  "  }",
  "",
  "  if (!parcel) {",
  "    let hist = null;",
  "    try {",
  "      hist = await ParcelHistory.findOne({",
  "        $or: [{ originalParcelId: idOrOrderId }, { _id: idOrOrderId }, { orderId: idOrOrderId }]",
  "      })",
  "      .populate('sender', 'firstName lastName email phone profilePhoto walletBalance rating senderPublicId isVerified')",
  "      .populate('acceptedBy', 'firstName lastName email phone profilePhoto walletBalance rating ratingCount travelerPublicId isVerified isOnline')",
  "      .populate('cancelledBy', 'firstName lastName email')",
  "      .lean();",
  "    } catch (e) {",
  "      hist = await ParcelHistory.findOne({ orderId: idOrOrderId })",
  "        .populate('sender', 'firstName lastName email phone profilePhoto walletBalance rating senderPublicId isVerified')",
  "        .populate('acceptedBy', 'firstName lastName email phone profilePhoto walletBalance rating ratingCount travelerPublicId isVerified isOnline')",
  "        .populate('cancelledBy', 'firstName lastName email')",
  "        .lean();",
  "    }",
  "",
  "    if (hist) {",
  "      parcel = adaptHistoryDoc(hist);",
  "    }",
  "  }",
  "",
  "  if (!parcel) return null;",
  "",
  "  const parcelObjId = parcel.originalParcelId || parcel._id;",
  "  const [walletTxns, relatedConversations] = await Promise.all([",
  "    WalletTransaction.find({",
  "      $or: [",
  "        { parcel: parcelObjId },",
  "        { orderId: parcel.orderId },",
  "        { referenceId: { $regex: parcel.orderId } }",
  "      ]",
  "    }).sort({ createdAt: -1 }).limit(20).lean(),",
  "    Conversation.find({",
  "      $or: [{ parcelId: parcelObjId }, { parcelId: parcel._id }]",
  "    }).populate('senderId', 'firstName lastName').populate('travelerId', 'firstName lastName').lean().catch(() => [])",
  "  ]);",
  "",
  "  const fraud = computeFraudScore(parcel);",
  "  const progressMap = { pending: 10, accepted: 25, pickup_confirmed: 50, in_transit: 75, delivered: 100, cancelled: 0 };",
  "",
  "  return {",
  "    parcel: {",
  "      ...parcel,",
  "      fraudScore: fraud.score,",
  "      fraudFlags: fraud.flags,",
  "      progress: progressMap[parcel.status] || (parcel.status === 'delivered' ? 100 : 0)",
  "    },",
  "    walletTransactions: walletTxns,",
  "    conversations: relatedConversations",
  "  };",
  "}",
  "",
  "/**",
  " * Federates outcomes (delivered + cancelled) for /api/admin/cancellations",
  " */",
  "async function getAdminOutcomes({ page = 1, limit = 20, outcome = 'all' }) {",
  "  const pageNum = Math.max(1, parseInt(page, 10) || 1);",
  "  const limitNum = Math.min(100, Math.max(1, parseInt(limit, 10) || 20));",
  "  const skip = (pageNum - 1) * limitNum;",
  "",
  "  const activeStatuses = outcome === 'cancelled' ? ['cancelled']",
  "    : outcome === 'delivered' ? ['delivered']",
  "    : ['cancelled', 'delivered'];",
  "",
  "  const historyFilter = {};",
  "  if (outcome !== 'all') {",
  "    historyFilter.finalStatus = outcome;",
  "  }",
  "",
  "  const [activeRows, activeTotal, historyRows, historyTotal] = await Promise.all([",
  "    PostParcel.find({ status: { $in: activeStatuses } })",
  "      .populate('sender', 'firstName lastName email')",
  "      .populate('cancelledBy', 'firstName lastName email')",
  "      .populate('acceptedBy', 'firstName lastName email')",
  "      .sort({ updatedAt: -1 })",
  "      .limit(pageNum * limitNum)",
  "      .lean(),",
  "    PostParcel.countDocuments({ status: { $in: activeStatuses } }),",
  "    ParcelHistory.find(historyFilter)",
  "      .populate('sender', 'firstName lastName email')",
  "      .populate('cancelledBy', 'firstName lastName email')",
  "      .populate('acceptedBy', 'firstName lastName email')",
  "      .sort({ completedAt: -1 })",
  "      .limit(pageNum * limitNum)",
  "      .lean(),",
  "    ParcelHistory.countDocuments(historyFilter)",
  "  ]);",
  "",
  "  const total = activeTotal + historyTotal;",
  "",
  "  const normalizedActive = activeRows.map(r => ({",
  "    _id: r._id,",
  "    orderId: r.orderId,",
  "    fromCity: r.fromCity,",
  "    toCity: r.toCity,",
  "    sender: r.sender,",
  "    status: r.status,",
  "    outcomeAt: r.status === 'cancelled' ? (r.cancelledAt || r.updatedAt) : (r.deliveredAt || r.updatedAt),",
  "    cancelledBy: r.cancelledBy || null,",
  "    cancellationFee: r.cancellationFee || 0,",
  "    cancellationReason: r.cancellationReason || '',",
  "    traveler: r.acceptedBy || null,",
  "    chargedAmount: r.chargedAmount || r.price || 0,",
  "    travelerEarning: r.travelerEarning || 0,",
  "    isArchived: false",
  "  }));",
  "",
  "  const normalizedHistory = historyRows.map(h => {",
  "    const s = h.snapshot || {};",
  "    return {",
  "      _id: h.originalParcelId || h._id,",
  "      orderId: h.orderId,",
  "      fromCity: s.fromCity || '',",
  "      toCity: s.toCity || '',",
  "      sender: h.sender,",
  "      status: h.finalStatus,",
  "      outcomeAt: h.completedAt || h.updatedAt,",
  "      cancelledBy: h.cancelledBy || null,",
  "      cancellationFee: s.cancellationFee || 0,",
  "      cancellationReason: s.cancellationReason || '',",
  "      traveler: h.acceptedBy || null,",
  "      chargedAmount: s.chargedAmount || s.price || 0,",
  "      travelerEarning: s.travelerEarning || 0,",
  "      isArchived: true",
  "    };",
  "  });",
  "",
  "  const unified = [...normalizedActive, ...normalizedHistory];",
  "  unified.sort((a, b) => new Date(b.outcomeAt || 0).getTime() - new Date(a.outcomeAt || 0).getTime());",
  "",
  "  const paged = unified.slice(skip, skip + limitNum);",
  "",
  "  return {",
  "    outcomes: paged,",
  "    total,",
  "    page: pageNum,",
  "    limit: limitNum,",
  "    totalPages: Math.ceil(total / limitNum) || 1",
  "  };",
  "}",
  "",
  "/**",
  " * Returns federated parcel statistics across active and history.",
  " */",
  "async function getAdminParcelStats() {",
  "  const [activeStats, historyDelivered, historyCancelled] = await Promise.all([",
  "    PostParcel.aggregate([",
  "      {",
  "        $group: {",
  "          _id: '$status',",
  "          count: { $sum: 1 }",
  "        }",
  "      }",
  "    ]),",
  "    ParcelHistory.countDocuments({ finalStatus: 'delivered' }),",
  "    ParcelHistory.countDocuments({ finalStatus: 'cancelled' })",
  "  ]);",
  "",
  "  const map = {",
  "    pending: 0,",
  "    accepted: 0,",
  "    pickup_confirmed: 0,",
  "    in_transit: 0,",
  "    delivered: historyDelivered,",
  "    cancelled: historyCancelled",
  "  };",
  "",
  "  activeStats.forEach(s => {",
  "    if (s._id === 'delivered') map.delivered += s.count;",
  "    else if (s._id === 'cancelled') map.cancelled += s.count;",
  "    else if (map.hasOwnProperty(s._id)) map[s._id] = s.count;",
  "  });",
  "",
  "  return map;",
  "}",
  "",
  "module.exports = {",
  "  findParcelAnywhere,",
  "  getAdminParcels,",
  "  getAdminParcelDetail,",
  "  getAdminOutcomes,",
  "  getAdminParcelStats,",
  "  adaptHistoryDoc",
  "};"
];

fs.writeFileSync(targetFile, lines.join('\n'), 'utf8');
console.log('Successfully written services/parcelLookup.js');
